version: "3"

services:
  database:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: baromap-database
      MYSQL_USER: root
      MYSQL_PASSWORD: Baromapbaromap$$
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: Baromapbaromap$$
    command: # 명령어 설정
      - --default-authentication-plugin=mysql_native_password
    ports: # 접근 포트 설정
      - 3305:3306 # Host:Container
    networks:
      - db_network
    restart: always  # 컨테이너 실행 시 재시작
  mytamla:
    build: .
    expose:
    - 8080
    depends_on:
      - database

networks: # 커스텀 네트워크 추가
  db_network: # 네트워크 이름
    driver: bridge