version: "3"

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx/mytamla:/var/log/nginx/mytamla
    ports:
      - "80:80"
      - "443:443"
    command:
      "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - baromap-server
  baromap-server:
    container_name: baromap
    image: davidolleh/baromap
    ports:
        - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/baromap
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Baromapbaromap$$
#      SPRING_PROFILES_ACTIVE: prod