name: CD
# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'oracle'


      #gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ### CD
      #배포를 위한 prod properties 설정
      - name: Make application-prod.yml
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "MYSQL_USERNAME_P: ${{ secrets.DB_USERNAME }}" >> ./application-prod.yml
          echo "MYSQL_PASSWORD_P: ${{ secrets.DB_PW }}" >> ./application-prod.yml
          echo "MYSQL_HOST_P: ${{ secrets.DB_HOST }}" >> ./application-prod.yml 
          echo "MYSQL_PORT_P: ${{ secrets.DB_HOST_PORT }}" >> ./application-prod.yml
          echo "MYSQL_DB_P: ${{ secrets.DB_NAME }}" >> ./application-prod.yml
          echo "SEARCH_ACCESS_KEY_P: ${{ secrets.SEARCH_ACCESS_KEY }}" >> ./application-prod.yml
          echo "SEARCH_URL_P: ${{ secrets.SEARCH_URL }}" >> ./application-prod.yml
          cat ./application-prod.yml
        shell: bash


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      #test를 제외한 프로젝트 빌드
      - name: Build With Gradle
        run: ./gradlew build -x test

      - name: Send docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu/"
#          script로 yml 파일 삭제하고 만들기

      #도커 빌드 & 이미지 push
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & Push
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/baromap .
          docker push ${{ secrets.DOCKER_REPO }}/baromap
      #docker-compose 파일을 ec2 서버에 배포
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker stop baromap
            docker rm baromap
            sudo docker pull ${{ secrets.DOCKER_REPO }}/baromap
            pwd
            ls -al
            sudo docker-compose up -d
#            sudo docker-compose
#            docker run -d --name baromap -p 8080:8080 ${{ secrets.DOCKER_REPO }}/baromap
#            docker rmi -f $(docker images -f "dangling=true" -q)